### ISSUE TITLE
clang-sys@1.7.0 error

### ISSUE THREAD

**Issue by MateoEmilio1** [availproject/avail-light#515]
When i use `cargo build --release` there's 2 errors of packages at compile time: (I already tried to fix it using `cargo add clang-sys` but it doesn't work )

error:

`The following warnings were emitted during compilation:

warning: clang-sys@1.7.0: could not execute llvm-config one or more times, if the LLVM_CONFIG_PATH environment variable is set to a full path to valid llvm-config executable it will be used to try to find an instance of libclang on your system: "couldn't execute llvm-config --prefix (path=llvm-config) (error: No such file or directory (os error 2))"

error: failed to run custom build command for clang-sys v1.7.0

Caused by:
  process didn't exit successfully: /home/tute/Desktop/avail/avail-light/target/release/build/clang-sys-d7c87b597cfa337e/build-script-build (exit status: 101)
  --- stdout
  cargo:warning=could not execute llvm-config one or more times, if the LLVM_CONFIG_PATH environment variable is set to a full path to valid llvm-config executable it will be used to try to find an instance of libclang on your system: "couldn't execute llvm-config --prefix (path=llvm-config) (error: No such file or directory (os error 2))"

  --- stderr
  thread 'main' panicked at /home/tute/.cargo/registry/src/[index.crates.io](https://index.crates.io/)-6f17d22bba15001f/clang-sys-1.7.0/build/dynamic.rs:206:45:
  called Result::unwrap() on an Err value: "couldn't find any valid shared libraries matching: ['[libclang.so](https://libclang.so/)', 'libclang-*.so'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (invalid: [])"
  note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for librocksdb-sys v0.11.0+8.1.1

Caused by:
  process didn't exit successfully: /home/tute/Desktop/avail/avail-light/target/release/build/librocksdb-sys-515f692c821472f5/build-script-build (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/tute/.cargo/registry/src/[index.crates.io](https://index.crates.io/)-6f17d22bba15001f/bindgen-0.65.1/lib.rs:603:31:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['[libclang.so](https://libclang.so/)', 'libclang-*.so', '[libclang.so](https://libclang.so/).*', 'libclang-*.so.*'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (invalid: [])"
  note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

any thoughts?

**Comment by SHAHBAZ533** [comment]
Public key?

**Comment by MateoEmilio1** [comment]
@vbhattaccmu of course! Ubuntu 22.04.3 LTS

Toolchain: rustup 1.27.0
 
rustc 1.77.1
cargo 1.77.1
